### ISSUE TITLE
New Test Issue for Examining Adaptive Card Schema

### ISSUE THREAD

**Issue by stevengum** [stevengum97/TrackedRepo#27]
Lorem ipsum dolor sit amet, sit modus novum an, fugit utamur repudiandae ne his, an tantas iisque nam. Mea at sonet assentior, sed ei suas sale. Alienum erroribus mei at. An est etiam efficiendi. Quo ut utroque imperdiet. Id vix sumo diam bonorum, te nam solum dicit.

Ad mel tamquam dignissim interpretaris, primis minimum fabellas duo ei. Sit in graece minimum deserunt. Eu populo labore vel, dico ornatus eu vix, mucius splendide te mea. Eu has offendit persecuti interesset, ne mei solum paulo meliore. Eu erat phaedrum pertinacia est. Ad zril suscipit reprimique has, ea eum civibus tacimates, id mea graeci legendos dissentias.

**Comment by stevengum97** [comment]
New Comment

**Comment by stevengum** [comment]
New Comment

**Comment by stevengum** [comment]
Has anyone else run into this issue?
